name             'deploy_guestbook'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures deploy_guestbook'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 'application'
depends 'application_ruby'
depends 'ruby_build'
depends 'user'
depends 'ssh_known_hosts'
depends 'runit'
depends 'poise'
depends 'poise-service'
depends 'poise-ruby'
depends 'poise-languages'
depends 'poise-archive'
# depends 'rvm'